#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.dump.MongoDumpMiddleware
  - wsp.downloadermws.check.CheckMiddleware
  - wsp.downloadermws.retry.RetryMiddleware
  - wsp.downloadermws.store.MongoStoreMiddleware
  - wsp.downloadermws.dedup.MongoDedupMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - project.spidermws.store.StoreMiddleware
  - wsp.spidermws.limitlevel.LimitLevelMiddleware

# ------ Spider -------
spiders:
  - project.spiders.search.SearchSpider
  - project.spiders.detail.DetailSpider


# ------ Start URLs ------
start_urls:
  - http://s.wanfangdata.com.cn/Paper.aspx?q=%E4%BF%A1%E5%B7%A5%E6%89%80&f=top
  - http://d.wanfangdata.com.cn/Periodical/dianzixb201406020

# ------ Properties ------
check:
  -
    url: "http://"
    succ: ""
    deny: ""
max_level: 1
max_retry_times: 3
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
dump_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
store_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
