#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.proxy.ProxyMiddleware
  - wsp.downloadermws.useragent.UserAgentMiddleware
  - project.downloadermws.retry.RetryMiddleware
  - wsp.downloadermws.xforward.XForwardMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - wsp.spidermws.dedup.MongoDedupMiddleware
  - wsp.spidermws.limitlevel.LimitLevelMiddleware
  - project.spidermws.store.StoreMiddleware

# ------ Spider -------
spiders:
  - project.spiders.search.SearchSpider
  - project.spiders.detail.DetailSpider

# ------ Start URLs ------
start_urls:

# ------ Properties ------
max_level: 1
max_retry_times: 10
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.90:27017
user_agent: "Mozilla/5.0 (iPad; CPU OS 9_3_1 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/49.0.2623.109 Mobile/13E238 Safari/601.1.46"
random_user_agent: True
proxy_agent_addr: 192.168.120.181:1234
