#-*- coding:utf-8 -*-

# ------ Downloader Plugins -------
downloader_plugins:
  - wsp.downloaderplugins.dedup.MongoDedupPlugin
  - wsp.downloaderplugins.check.CheckPlugin
  - wsp.downloaderplugins.dump.MongoDumpPlugin
  - wsp.downloaderplugins.store.MongoStorePlugin
  - wsp.downloaderplugins.retry.RetryPlugin

# ------ Spider Plugins -------
spider_plugins:
  - wsp.spiderplugins.levellimit.LevelLimitPlugin

# ------ Spider -------
spider: project.spider.WanFangSpider

# ------ Start URLs ------
start_urls:
  - http://www.iie.ac.cn
  - http://cfb.bd.gov.cn
  - http://www.iie.ac.cn

# ------ Properties ------
check:
  -
    url: "http://"
    succ: ""
    deny: ""
max_level: 0
max_retry_times: 3
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
dump_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
store_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
