#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.dedup.MongoDedupMiddleware
  - wsp.downloadermws.check.CheckMiddleware
  - wsp.downloadermws.dump.MongoDumpMiddleware
  - wsp.downloadermws.store.MongoStoreMiddleware
  - wsp.downloadermws.retry.RetryMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - wsp.spidermws.levellimit.LevelLimitMiddleware

# ------ Spider -------
spider: project.spider.WanFangSpider

# ------ Start URLs ------
start_urls:
  - http://www.iie.ac.cn
  - http://cfb.bd.gov.cn
  - http://www.iie.ac.cn

# ------ Properties ------
check:
  -
    url: "http://"
    succ: ""
    deny: ""
max_level: 0
max_retry_times: 3
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
dump_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
store_mongo_addr: mongodb://wsp:wsp123456@192.168.120.181:27017
