#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.useragent.UserAgentMiddleware
  - project.downloadermws.retry.RetryMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - wsp.spidermws.dedup.MongoDedupMiddleware
  - project.spidermws.store.StoreMiddleware

# ------ Spider -------
spiders:
  - project.spiders.search.SearchSpider

# ------ Start URLs ------
start_urls:

# ------ Properties ------
max_retry_times: 10
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.90:27017
random_user_agent: True
