#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.proxy.ProxyMiddleware
  - project.downloadermws.retry.RetryMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - wsp.spidermws.dedup.MongoDedupMiddleware
  - wsp.spidermws.limitlevel.LimitLevelMiddleware
  - project.spidermws.store.StoreMiddleware

# ------ Spider -------
spiders:
  - project.spiders.search.SearchSpider
  - project.spiders.detail.DetailSpider

# ------ Start URLs ------
start_urls:

# ------ Properties ------
max_level: 1
max_retry_times: 10
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.90:27017
store_mongo_addr: mongodb://wsp:wsp123456@192.168.120.90:27017
proxy_agent_addr: 192.168.120.181:1234
