#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.useragent.UserAgentMiddleware
  - project.downloadermws.retry.RetryMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - wsp.spidermws.dedup.MongoDedupMiddleware
#  - wsp.spidermws.limitlevel.LimitLevelMiddleware
  - project.spidermws.store.StoreMiddleware

# ------ Spider -------
spiders:
  - project.spiders.search.SearchSpider
#  - project.spiders.detail.DetailSpider

# ------ Start URLs ------
start_urls:

# ------ Properties ------
random_user_agent: True
#max_level: 1
max_retry_times: 10
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.90:27017
#dedup_mongo_db: wanfang_dedup
#dedup_mongo_coll: iie_dedup
