#-*- coding:utf-8 -*-

# ------ Downloader Middlewares -------
downloader_middlewares:
  - wsp.downloadermws.proxy.ProxyMiddleware
  - wsp.downloadermws.useragent.UserAgentMiddleware
  - project.downloadermws.retry.RetryMiddleware

# ------ Spider Middlewares -------
spider_middlewares:
  - wsp.spidermws.dedup.MongoDedupMiddleware
  - project.spidermws.store.StoreMiddleware

# ------ Spider -------
spiders:
  - project.spiders.search.SearchSpider

# ------ Start URLs ------
start_urls:

# ------ Properties ------
max_retry_times: 10
dedup_mongo_addr: mongodb://wsp:wsp123456@192.168.120.90:27017
user_agent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36"
random_user_agent: True
proxy_agent_addr: 192.168.120.181:1234
